### ISSUE TITLE
Question: Freezing encoder with Mask2Former decoder

### ISSUE THREAD

**Issue by ioangatop** [tue-mps/benchmark-vfm-ss#1]
Hi, fir of all, thank you for the great work and for open sourcing the code!

I would like to ask if you conduct any experiments by freezing encoder while using the Mask2Former decoder. If so, what did you observe? 

Thank you

**Comment by tommiekerssies** [comment]
In all our experiments with VFMs for image segmentation we have not found a single case where freezing the encoder is beneficial. Also under limited data or large distribution shifts. We have not extensively explored partial freezing or adapters though. So Mask2Former with a frozen encoder does not help much beyond a linear layer. However, please note that Mask2Former does not update the patch tokens anymore, all it does is update query tokens by cross-attending to the patch tokens.

**Comment by tommiekerssies** [comment]
Hi @ioangatop, I have just conducted an experiment with **DINOv2 ViT-B** with a **frozen encoder** and a **Mask2Former decoder**, which I have highlighted in bold below, along with the other relevant results in the paper:

- ADE20K Mask2Former (DINOv2 ViT-B):                 54.8%
- ADE20K Linear (DINOv2 ViT-B):                              53.4%
- **ADE20K Mask2Former (Frozen DINOv2 ViT-B): 51.2%**
- ADE20K Linear (Frozen DINOv2 ViT-B):                 45.8%

**Comment by ioangatop** [comment]
@tommiekerssies thank you very much, this is very interested! How was in terms of training time compare to the others?

**Comment by tommiekerssies** [comment]
@ioangatop I cannot give you a very accurate comparison in training time, because I ran this experiment on a different machine. However, it is pretty similar to the training time of Mask2Former with end-to-end fine-tuning.
